Document how to update to a new batou 2.x version.
flyingcircusio/batou pull request #105
Opened 2020-10-13 06:03 UTC by icemac

Fixes #103.

2020-11-09 07:57 UTC, ctheune requested changes
Looks good! Minor wording issue that I'd like corrected, though.

2020-11-09 07:57 UTC, ctheune commented on doc/source/upgrading.txt
> +    - If you want to use a not released version use a git URL like this:
wording: "not release" -> unreleased

2020-11-11 07:42 UTC, icemac commented on doc/source/upgrading.txt
> +    - If you want to use a not released version use a git URL like this:
Fixed.

2020-11-12 07:13 UTC, icemac commented
Hm, the tests are broken on GH Actions but it does not seem to be my fault.

2020-11-12 07:31 UTC, ctheune commented
Yeah, no worries. I moved to GA earlier this week but didn't get everything done back then. I'll fix those later.

2020-11-12 07:31 UTC, merged