re #89: Avoid implicit conversion of Attribute defaults.
flyingcircusio/batou pull request #200
Opened 2021-07-14 05:51 UTC by sallner

As Attributes are data descriptors it is not possible to get the conversion function from the attribute alone. We need to check on the parent component for it. This made it necessary to adapt code, which sets defaults and overrides on Attributes.

When this PR is merged, we need to adapt https://github.com/flyingcircusio/batou_ext.

2021-07-14 20:21 UTC, sallner commented
@zagy @ctheune The error is caused because the key cannot be added to the secrets after removal. This is most probably the case, because the key is not valid in the `trustdb.gpg`. This file is also render ed as modified, when tests were running on a local machine. So it could be a solution to add the key again to the `trustdb.gpg`. https://github.com/flyingcircusio/batou/commit/71177b18b96d65e1a01618e17aea75ac22b62879 seems not to be enough.

2021-07-17 08:33 UTC, ctheune commented
This should be fixed on master now, please try rebasing.

2021-07-19 06:05 UTC, icemac commented
This PR is now ready for review as the tests pass.

2021-09-16 07:23 UTC, ctheune requested changes

2021-09-24 07:34 UTC, sallner commented on src/batou/lib/file.py
> +            Mode_ = Mode(self.path)
I rebased your changes for this PR.

2021-09-24 07:39 UTC, sallner commented on CHANGES.md
> +
Yes, we also have to remind the user that https://github.com/flyingcircusio/batou_ext has also to be updated.

2021-09-24 17:11 UTC, sallner commented on src/batou/tests/test_deploy.py
> + Exception: Attributes only support one of those parameters: `default` or `default_conf_string`.
✅

2021-09-24 17:12 UTC, sallner commented on src/batou/component.py
> +                self,
✅

2021-09-24 17:31 UTC, sallner commented on CHANGES.md
> +
I added some hopefully helpful words and added a section to indicate the tricky changes.

2021-10-05 11:09 UTC, merged