Allow to pin the `pip` version used in the `Buildout` component.
flyingcircusio/batou pull request #263
Opened 2021-12-09 10:13 UTC by icemac

2021-12-09 10:30 UTC, sallner requested changes

2021-12-09 10:30 UTC, sallner commented on src/batou/lib/buildout.py
> +            venv.venv.install_options = ()
```suggestion
```
I hope, we can leave that out, as https://github.com/flyingcircusio/batou/commit/41cb58b8d9cb7af4675a51f6b8ed991d37bf6955#diff-e81661b692ea23dd37b493a40c3c5582b2e50ac0858309fe72fc02c9644f4eee was already merged. This seems to be a relict from before that time.

2022-01-10 08:51 UTC, ctheune commented
Actually, I think we should remove the `--ignore-installed` completely and maybe replace it with `--force-reinstall`.  Not sure what downwards compatibility force-reinstall requires, though.

2022-01-18 13:21 UTC, sallner approved these changes
Now it looks good for me.

2022-03-07 10:04 UTC, merged