increase supervisor buildout and setuptools versions for support for newer python
flyingcircusio/batou pull request #379
Opened 2023-07-07 13:27 UTC by elikoga

closes #366

2024-04-17 12:04 UTC, zagy commented
@elikoga is this still relevant, or was it (maybe) updated otherwise?

2024-04-23 09:16 UTC, elikoga commented
This one is part of a larger python 3.10 upgrade thing, so it has stalled a bit

2024-05-28 09:35 UTC, zagy requested changes

2024-06-20 09:35 UTC, zagy approved these changes

2024-06-20 09:36 UTC, merged