fix: SyncDirectory verification
flyingcircusio/batou pull request #410
Opened 2023-11-28 13:13 UTC by PhilTaken

Add a check to the SyncDirectory component for the target directory.

The SyncDirectory component `verify()` stage fails when the target directory does not exist yet, because it uses rsync to determine if there is a diff between left and right. In cases where the target directory is part of the deployment and has thusly not been created yet, this leads to unexpected errors.

2023-11-29 09:40 UTC, ctheune requested changes
Looks good in general, but could you please add a test case?

2023-12-06 15:28 UTC, PhilTaken commented
> Looks good in general, but could you please add a test case?

done

2023-12-06 15:32 UTC, ctheune commented
Great. Thanks!

@elikoga can you merge and backport?

2023-12-06 16:11 UTC, elikoga commented
@ctheune I can open a backport PR, but merging is restricted for me

2023-12-06 19:38 UTC, merged