Track component initialisations for error messages
flyingcircusio/batou pull request #420
Opened 2023-12-19 00:55 UTC by elikoga

closes #278 

provides a warning if a component is initialized, but not prepared:

Say we have the `tutorial-helloworld`:
`component.py`:
```python
class Hello(Component):
    def configure(self):
        self += File("hello", content="Hello world")
        File("")
```

This gives us an error message like this: 
```
batou/2.5.dev0 (cpython 3.7.16-final0, Darwin 23.1.0 arm64)
================================== Preparing ===================================
main: Loading environment `tutorial`...
main: Verifying repository ...
main: Loading secrets ...
================== Connecting hosts and configuring model ... ==================
localhost: Connecting via local (1/1)
WARN: A Component 'File' was initialized but was not prepared (configured).
This may not be what you want
================================== Deploying ===================================
localhost: Scheduling component hello ...
=================================== Summary ====================================
Deployment took total=0.23s, connect=0.23s, deploy=0.00s
============================= DEPLOYMENT FINISHED ==============================
```

Of course the warning is yellow too:

![image](https://github.com/flyingcircusio/batou/assets/37669174/24c4820f-ee2e-437b-9332-6eda5a5a46ec)

2023-12-19 06:30 UTC, ctheune approved these changes

2023-12-19 06:30 UTC, ctheune commented on src/batou/environment.py
> +        # if any of Component.instances has ._prepared == False, then
I would actually make this an error in the configuration phase as this is against the consistency we want to guarantee.

2023-12-19 06:30 UTC, ctheune submitted a review, later dismissed
See the note about that this should be erroring out instead of just warning.

2024-02-28 10:10 UTC, ctheune commented
What does the output look like now? Does the user have a chance to figure out where this happened? (We can keep track of the call stack during __init__ and then use that to indicate the problem later.)

2024-04-19 05:08 UTC, zagy requested changes
The changelog is missing.

2024-04-23 09:17 UTC, elikoga commented
> We can keep track of the call stack during init and then use that to indicate the problem later.)

PR doesn't included that yet so I'll draft this one

2024-06-20 01:49 UTC, elikoga commented
Currently looks like this:

On input:
```python
from batou.component import Component
from batou.lib.file import File


class Hello(Component):
    def configure(self):
        self += File("hello", content="Hello world")
        self += FooComponent()


class FooComponent(Component):
    def configure(self):
        BarComponent()


class BarComponent(Component):
    pass
```

```
batou/2.5.0b3.dev0 (cpython 3.11.9-final0, Darwin 23.5.0 arm64)
================================================= Preparing =================================================
main: Loading environment `tutorial`...
main: Verifying repository ...
main: Loading secrets ...
================================ Connecting hosts and configuring model ... =================================
localhost: Connecting via local (1/1)
WARN: Unused components: 
    'BarComponent': Hello -> FooComponent
================================================= Deploying =================================================
localhost: Scheduling component hello ...
================================================== Summary ==================================================
Deployment took total=0.24s, connect=0.24s, deploy=0.00s
============================================ DEPLOYMENT FINISHED ============================================
```

<img width="770" alt="image" src="https://github.com/flyingcircusio/batou/assets/37669174/8045c190-6b86-4938-8e48-2cd0d268914f">

2024-06-20 09:23 UTC, zagy approved these changes

2024-06-20 09:26 UTC, zagy requested changes
The warning message should be improved:

* e.g. Component was not added. `self += …` missing?
* We know the file and line number from the stack, put it out.

2024-06-25 02:12 UTC, elikoga commented
![image](https://github.com/flyingcircusio/batou/assets/37669174/38174208-e64f-4717-b66c-4b47699724a4)
This is what the output looks like now

2024-06-25 09:36 UTC, zagy approved these changes

2024-06-25 09:38 UTC, zagy commented
> See the note about that this should be erroring out instead of just warning.

We *don't* want to have an error here. We just don't know what people are doing out there and having an error where you have no means of getting out of it is bad.

2024-06-25 09:39 UTC, merged