Batou secrets diffable
flyingcircusio/batou pull request #440
Opened 2024-01-30 09:37 UTC by elikoga

New settings format for 2.5

2024-02-28 09:53 UTC, ctheune commented
I'd like to review this together. I'm wondering whether to make this a straight-forward migration and not keep two separate mechanisms around?

2024-03-13 09:18 UTC, ctheune requested changes

2024-03-13 09:18 UTC, ctheune commented on src/batou/secrets/encryption.py
> +                    not reencrypt
This is hard to read, I suggest two changes: a) make the happy path go first and b) extract the conditions into easier-to-read variables:

```python
new_value = config[section][option].value
assert new_value is not None

try:
    old_value = self._decrypted_content[section][option].value
except Exception:
    old_value = None

value_has_changed = new_value != old_value

if (reencrypt or value_has_changed):
    new_encrypted_value = self.encrypt_age_string(new_value, recipients)
else:
    new_encrypted_value = self._encrypted_content[section][option].value

config[section][option].value = new_encrypted_value
```

2024-04-17 12:10 UTC, zagy approved these changes

2024-04-17 12:27 UTC, merged