Add variable `batou_generated_header` to global template rendering context
flyingcircusio/batou pull request #465
Opened 2024-08-13 08:35 UTC by elikoga

Closes #356

The string could also include information such as the current batou version.

2024-08-13 09:41 UTC, elikoga commented
- no comment start, only string in header
- add information: which component generates this file

2024-08-20 09:38 UTC, zagy requested changes

2024-08-20 09:38 UTC, zagy commented on src/batou/component.py
> +            batou_generated_header=batou_generated_header(component),
Please add the new variable to the docstring, too.

2024-09-03 09:32 UTC, zagy approved these changes

2024-09-03 09:32 UTC, merged