Configure usage of `tox`
flyingcircusio/batou pull request #95
Opened 2020-09-29 12:37 UTC by jugmac00

Examples:

- run tests for Python 3.6
`tox -e py36`

- run tests for Python 3.7 and Python 3.9
`tox -e py37 -e py39`

- run only the git tests on Python 3.8
`tox -e py38 -- -k test_git`

modified:   setup.py
modified:   src/batou/tests/test_remote_core.py
new file:   tox.ini

2020-09-29 12:41 UTC, jugmac00 commented
I had to set environment variables to configure git (ie. author_email and contributor_email) - that has nothing to do with tox. I assume in other test environments the mentioned configuration leaked into the test and thus the tests worked accidentally.

2020-10-14 06:17 UTC, icemac reviewed
I like these changes and it would be nice to get them merged.

Maybe `tox` should be mentioned in the documentation about how to develop on `batou` itself. (I did not look up of there is already such a section.)

2020-11-09 07:56 UTC, ctheune requested changes

2020-11-09 08:23 UTC, merged

2020-11-09 08:28 UTC, jugmac00 commented
Hmkay, I was about making sure the other tests also run...

There were some new failures because of not-blackend code.

And I have a couple failing/erroring tests - but only on Python 3.5.

I will start over from master, and file issues, if necessary.